server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: backend1
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://127.0.0.1:5432/employee_attendance_db}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: ${JWT_SECRET:your-super-secret-jwt-key-change-this}
  expiration-ms: 86400000 # 24 hours

logging:
  level:
    root: INFO
    com.hrchomnan.backend1: INFO
