import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

const translations = {
  en: {
    // Nav & Sidebar
    dashboard: "Dashboard",
    departments: "Departments",
    positions: "Positions",
    employees: "Employees",
    attendance: "Attendance Log",
    leaveGroup: "Leave",
    requestItem: "Request",
    types: "Types",
    allowances: "Allowances",
    setupGroup: "Setup",
    workHours: "Work Hours",
    telegramGroup: "Telegram Group",
    reports: "Reports",
    facescan: "Facescan",
    checkAttendance: "Check Attendance",
    facescanMode: "Facescan Mode",
    qrscanMode: "QR Code Scan",
    branchSetting: "Branch",
    logout: "Log Out",
    welcome: "Welcome back",
    role: "Role",

    // Dashboard
    totalEmployees: "Total Employees",
    presentToday: "Present Today",
    lateToday: "Late Today",
    earlyLeaveToday: "Early Leave Today",
    onLeaveToday: "On Leave Today",
    attendanceSummary: "Today's Live Attendance",
    liveConsole: "Attendance Console",
    checkin1: "Check-in 1",
    checkout1: "Check-out 1",
    checkin2: "Check-in 2",
    checkout2: "Check-out 2",
    notLogged: "Not Logged",
    normal: "On Time",
    late: "Late",
    earlyLeave: "Early Leave",
    allAttendanceLogs: "All Logs",
    earlyArrivals: "Early In",
    lateArrivals: "Late",
    earlyDepartures: "Early Out",
    earlyInRecords: "Early In Attendance Records",
    lateRecords: "Late Attendance Records",
    earlyOutRecords: "Early Out Attendance Records",
    logAttendanceSuccess: "Attendance logged successfully!",

    // General Actions
    date: "Date",
    add: "Add New",
    edit: "Edit",
    delete: "Delete",
    save: "Save",
    cancel: "Cancel",
    actions: "Actions",
    search: "Search...",
    filter: "Filter",
    clear: "Clear",
    all: "All",
    status: "Status",
    branch: "Branch",
    submit: "Submit",
    loading: "Loading...",
    noData: "No data available",
    confirmDelete: "Are you sure you want to delete this item?",

    // Departments & Positions
    deptNameEn: "Department Name (EN)",
    deptNameKh: "Department Name (KH)",
    description: "Description",
    posTitleEn: "Position Title (EN)",
    posTitleKh: "Position Title (KH)",
    selectDept: "Select Department",

    // Employees
    staffId: "Staff ID",
    nameEn: "Name (EN)",
    nameKh: "Name (KH)",
    gender: "Gender",
    joinDate: "Join Date",
    email: "Email",
    password: "Password",
    shift1: "Shift 1",
    shift2: "Shift 2",
    shiftConfig: "Shift Times Configuration",
    enableTwoShifts: "Enable 2 Shifts",
    twoShiftsDesc: "Toggle on to configure 2 shifts, or off for a single shift.",
    twoShifts: "2 Shifts",
    singleShift: "1 Shift",
    flexibleHours: "Flexible Working Hours",
    flexibleHoursDesc: "Configure flexible or rotating work hours day-by-day for the entire month.",
    fixedShifts: "Fixed Shifts",
    fixedShiftsDesc: "Set fixed regular daily working shift times.",
    monthSchedule: "Monthly Flexible Schedule",
    workingDaysWeekly: "Working Days",
    workingDaysDesc: "Select standard working days of the week (Monday - Sunday) to apply.",
    dayOff: "Day Off",
    workingDay: "Working Day",
    quickPresets: "Quick Presets & Actions",
    applyToAllDays: "Apply to All Days",
    applyWeekdays: "Mon - Fri Only",
    setWeekendsOff: "Weekends Off",
    rotatePattern: "Rotate Shift Pattern",
    clearMonth: "Reset Month",
    day: "Day",
    noteOrLabel: "Shift Label",
    totalWorkingDays: "Working Days",
    totalDaysOff: "Days Off",
    selectMonth: "Select Month",
    start: "Start",
    end: "End",
    male: "Male",
    female: "Female",
    other: "Other",
    active: "Active",
    inactive: "Inactive",
    suspended: "Suspended",
    address: "Address",
    idCardPassport: "ID Card / Passport",
    uploadPhoto: "Upload Photo",
    capturePhoto: "Capture Photo",
    viewProfile: "View Profile",
    faceEnrolled: "Face Enrolled",
    faceNotEnrolled: "Face Not Enrolled",
    profile: "Profile",

    // Leaves
    leaveType: "Leave Type",
    leaveDate: "Leave Date",
    amountDays: "Duration (Days)",
    reason: "Reason",
    managerName: "Approved By",
    requestLeave: "Request Leave",
    approvalManage: "Approval Manage",
    approve: "Approve",
    reject: "Reject",
    pending: "Pending",
    approved: "Approved",
    rejected: "Rejected",
    annualLeave: "Annual Leave",
    sickLeave: "Sick Leave",
    personalLeave: "Personal Leave",

    // Overtime
    overtime: "Overtime",
    overtimeSubtitle: "Manage and track employee overtime requests and approvals",
    requestOvertime: "Request Overtime",
    totalRequests: "Total Requests",
    pendingRequests: "Pending",
    approvedRequests: "Approved",
    rejectedRequests: "Rejected",
    totalApprovedDays: "Total Approved Days",
    searchPlaceholderOvertime: "Search by name, staff ID, reason...",
    allStatus: "All Status",
    allBranches: "All Branches",
    selectBranch: "Select Branch",
    employee: "Employee",
    manager: "Manager",
    fromDate: "From Date",
    toDate: "To Date",
    startTime: "Start Time",
    endTime: "End Time",
    amountDay: "Amount Day",
    comment: "Comment",
    requestedAt: "Requested At",
    approvedAt: "Approved At",
    createdBy: "Created By",
    daysUnit: "days",
    dayUnit: "day",
    noOvertimeData: "No overtime records found",
    approveOvertimeTitle: "Approve Overtime",
    rejectOvertimeTitle: "Reject Overtime",
    managerCommentPlaceholder: "Write comment or note here...",
    managerCommentLabel: "Manager Comment",
    overtimeAutoCalculateHint: "Auto-calculated: 8 hours = 1 day or edit manually",
    reasonRequiredError: "Reason is required",
    fillRequiredDatesError: "Please fill all required date and time fields",

    // Reports
    attendanceReport: "Attendance & Leaflet Report",
    startDate: "Start Date",
    endDate: "End Date",
    exportExcel: "Export Excel",
    printPdf: "Print / PDF Report",
    searchFilter: "Search & Filters",
  },
  kh: {
    // Nav & Sidebar
    dashboard: "ផ្ទាំងគ្រប់គ្រង",
    departments: "ដេប៉ាតឺម៉ង់",
    positions: "តួនាទី",
    employees: "បុគ្គលិក",
    attendance: "កំណត់ត្រាវត្តមាន",
    leaveGroup: "ច្បាប់សម្រាក",
    requestItem: "ស្នើសុំច្បាប់",
    types: "ប្រភេទច្បាប់",
    allowances: "ចំនួនថ្ងៃច្បាប់អនុញ្ញាត",
    setupGroup: "ការកំណត់ប្រព័ន្ធ",
    workHours: "ម៉ោងការងារ",
    telegramGroup: "Telegram Group",
    reports: "របាយការណ៍",
    facescan: "ស្កេនផ្ទៃមុខ",
    checkAttendance: "ចុះវត្តមាន",
    facescanMode: "ស្កេនផ្ទៃមុខ",
    qrscanMode: "ស្កេន QR Code",
    branchSetting: "សាខា",
    logout: "ចាកចេញ",
    welcome: "ស្វាគមន៍ការត្រឡប់មកវិញ",
    role: "តួនាទីគណនី",

    // Dashboard
    totalEmployees: "បុគ្គលិកសរុប",
    presentToday: "វត្តមានថ្ងៃនេះ",
    lateToday: "មកយឺតថ្ងៃនេះ",
    earlyLeaveToday: "ចេញមុនថ្ងៃនេះ",
    onLeaveToday: "ច្បាប់ថ្ងៃនេះ",
    attendanceSummary: "វត្តមានផ្ទាល់ថ្ងៃនេះ",
    liveConsole: "ផ្ទាំងបញ្ជាវត្តមាន",
    checkin1: "ចូលវេនទី ១",
    checkout1: "ចេញវេនទី ១",
    checkin2: "ចូលវេនទី ២",
    checkout2: "ចេញវេនទី ២",
    notLogged: "មិនទាន់ចុះ",
    normal: "ទាន់ពេល",
    late: "មកយឺត",
    earlyLeave: "ចេញមុន",
    allAttendanceLogs: "កំណត់ត្រាវត្តមានទាំងអស់",
    earlyArrivals: "មកមុនម៉ោង (Early In)",
    lateArrivals: "មកយឺត (Late)",
    earlyDepartures: "ចេញមុនម៉ោង (Early Out)",
    earlyInRecords: "កំណត់ត្រាបុគ្គលិកមកមុនម៉ោង (Early In)",
    lateRecords: "កំណត់ត្រាបុគ្គលិកមកយឺត (Late)",
    earlyOutRecords: "កំណត់ត្រាបុគ្គលិកចេញមុនម៉ោង (Early Out)",
    logAttendanceSuccess: "បានកត់ត្រាវត្តមានជោគជ័យ!",

    // General Actions
    date: "កាលបរិច្ឆេទ",
    add: "បន្ថែមថ្មី",
    edit: "កែប្រែ",
    delete: "លុប",
    save: "រក្សាទុក",
    cancel: "បោះបង់",
    actions: "សកម្មភាព",
    search: "ស្វែងរក...",
    filter: "ចម្រោះ",
    clear: "សម្អាត",
    all: "ទាំងអស់",
    status: "ស្ថានភាព",
    branch: "សាខា",
    submit: "បញ្ជូន",
    loading: "កំពុងដំណើរការ...",
    noData: "មិនមានទិន្នន័យទេ",
    confirmDelete: "តើអ្នកប្រាកដជាចង់លុបទិន្នន័យនេះមែនទេ?",

    // Departments & Positions
    deptNameEn: "ឈ្មោះដេប៉ាតឺម៉ង់ (EN)",
    deptNameKh: "ឈ្មោះដេប៉ាតឺម៉ង់ (KH)",
    description: "ការពិពណ៌នា",
    posTitleEn: "ឈ្មោះតួនាទី (EN)",
    posTitleKh: "ឈ្មោះតួនាទី (KH)",
    selectDept: "ជ្រើសរើសដេប៉ាតឺម៉ង់",

    // Employees
    staffId: "អត្តលេខ",
    nameEn: "ឈ្មោះ (EN)",
    nameKh: "ឈ្មោះ (KH)",
    gender: "ភេទ",
    joinDate: "ថ្ងៃចូលបម្រើការងារ",
    email: "អ៊ីមែល",
    password: "លេខសម្ងាត់",
    selectPos: "ជ្រើសរើសតួនាទី",
    shift1: "វេនទី ១",
    shift2: "វេនទី ២",
    shiftConfig: "ការកំណត់ម៉ោងវេនការងារ",
    enableTwoShifts: "កំណត់ ២ វេន",
    twoShiftsDesc: "បើកដើម្បីកំណត់ ២ វេន ឬបិទដើម្បីកំណត់ត្រឹមតែ ១ វេន",
    twoShifts: "២ វេន",
    singleShift: "១ វេន",
    flexibleHours: "ម៉ោងធ្វើការបត់បែនតាមថ្ងៃ (Flexible)",
    flexibleHoursDesc: "កំណត់ម៉ោងធ្វើការបត់បែន ឬឆ្លាស់គ្នាតាមថ្ងៃសម្រាប់មួយខែពេញ។",
    fixedShifts: "ម៉ោងវេនថេរ (Fixed Shifts)",
    fixedShiftsDesc: "កំណត់ម៉ោងវេនធ្វើការថេរប្រចាំថ្ងៃ។",
    monthSchedule: "កាលវិភាគម៉ោងធ្វើការប្រចាំខែ",
    workingDaysWeekly: "កំណត់ថ្ងៃធ្វើការ (Working Days)",
    workingDaysDesc: "ជ្រើសរើសថ្ងៃធ្វើការប្រចាំសប្ដាហ៍ (ចន្ទ - អាទិត្យ) ដើម្បីកំណត់ស្វ័យប្រវត្តក្នុងខែ។",
    dayOff: "ថ្ងៃសម្រាក",
    workingDay: "ថ្ងៃធ្វើការ",
    quickPresets: "ឧបករណ៍កំណត់រហ័ស",
    applyToAllDays: "អនុវត្តគ្រប់ថ្ងៃទាំងអស់",
    applyWeekdays: "អនុវត្តតែថ្ងៃ ចន្ទ-សុក្រ",
    setWeekendsOff: "ដាក់ សៅរ៍-អាទិត្យ សម្រាក",
    rotatePattern: "ឆ្លាស់វេន (ព្រឹក/ល្ងាច/សម្រាក)",
    clearMonth: "សម្អាតកាលវិភាគ",
    day: "ថ្ងៃទី",
    noteOrLabel: "សម្គាល់វេន",
    totalWorkingDays: "ថ្ងៃធ្វើការ",
    totalDaysOff: "ថ្ងៃសម្រាក",
    selectMonth: "ជ្រើសរើសខែ",
    start: "ម៉ោងចូល",
    end: "ម៉ោងចេញ",
    male: "ប្រុស",
    female: "ស្រី",
    other: "ផ្សេងៗ",
    active: "កំពុងធ្វើការ",
    inactive: "ឈប់ធ្វើការ",
    suspended: "ផ្អាកបណ្តោះអាសន្ន",
    address: "អាសយដ្ឋាន",
    idCardPassport: "អត្តសញ្ញាណប័ណ្ណ / លិខិតឆ្លងដែន",
    uploadPhoto: "ផ្ទុកឡើងរូបភាព",
    capturePhoto: "ថតរូបភាព",
    viewProfile: "មើលប្រវត្តិរូប",
    faceEnrolled: "បានចុះឈ្មោះផ្ទៃមុខ",
    faceNotEnrolled: "មិនទាន់ចុះឈ្មោះផ្ទៃមុខ",
    profile: "ប្រវត្តិរូប",

    // Leaves
    leaveType: "ប្រភេទច្បាប់",
    leaveDate: "ថ្ងៃសុំច្បាប់",
    amountDays: "ចំនួនថ្ងៃច្បាប់",
    reason: "មូលហេតុ",
    managerName: "អនុម័តដោយ",
    requestLeave: "ស្នើសុំច្បាប់",
    approvalManage: "កំណត់អ្នកអនុម័ត",
    approve: "អនុម័ត",
    reject: "បដិសេធ",
    pending: "កំពុងរង់ចាំ",
    approved: "បានអនុម័ត",
    rejected: "បានបដិសេធ",
    annualLeave: "ច្បាប់សម្រាកប្រចាំឆ្នាំ",
    sickLeave: "ច្បាប់ឈឺ",
    personalLeave: "ច្បាប់ផ្ទាល់ខ្លួន",

    // Overtime
    overtime: "ថែមម៉ោង",
    overtimeSubtitle: "គ្រប់គ្រង និងតាមដានសំណើសុំថែមម៉ោងរបស់បុគ្គលិក",
    requestOvertime: "ស្នើសុំថែមម៉ោង",
    totalRequests: "សំណើសរុប",
    pendingRequests: "កំពុងរង់ចាំ",
    approvedRequests: "បានអនុម័ត",
    rejectedRequests: "បានបដិសេធ",
    totalApprovedDays: "ចំនួនថ្ងៃអនុម័តសរុប",
    searchPlaceholderOvertime: "ស្វែងរកតាមឈ្មោះ អត្តលេខ មូលហេតុ...",
    allStatus: "ស្ថានភាពទាំងអស់",
    allBranches: "សាខាទាំងអស់",
    selectBranch: "ជ្រើសរើសសាខា",
    employee: "បុគ្គលិក",
    manager: "អ្នកគ្រប់គ្រង",
    fromDate: "ថ្ងៃចាប់ផ្តើម",
    toDate: "ថ្ងៃបញ្ចប់",
    startTime: "ម៉ោងចាប់ផ្តើម",
    endTime: "ម៉ោងបញ្ចប់",
    amountDay: "ចំនួនថ្ងៃ",
    comment: "មតិយោបល់",
    requestedAt: "កាលបរិច្ឆេទស្នើសុំ",
    approvedAt: "កាលបរិច្ឆេទអនុម័ត",
    createdBy: "បង្កើតដោយ",
    daysUnit: "ថ្ងៃ",
    dayUnit: "ថ្ងៃ",
    noOvertimeData: "មិនមានទិន្នន័យថែមម៉ោងឡើយ",
    approveOvertimeTitle: "អនុម័តថែមម៉ោង",
    rejectOvertimeTitle: "បដិសេធថែមម៉ោង",
    managerCommentPlaceholder: "សរសេរមតិយោបល់ ឬចំណាំនៅទីនេះ...",
    managerCommentLabel: "មតិយោបល់របស់អ្នកគ្រប់គ្រង",
    overtimeAutoCalculateHint: "គណនាស្វ័យប្រវត្តិតាមម៉ោងថែម៖ ៨ ម៉ោង = ១ ថ្ងៃ ឬកែប្រែដោយដៃ",
    reasonRequiredError: "សូមបញ្ចូលមូលហេតុនៃការថែមម៉ោង",
    fillRequiredDatesError: "សូមបំពេញកាលបរិច្ឆេទ និងម៉ោងចាប់ផ្តើម/បញ្ចប់",

    // Reports
    attendanceReport: "របាយការណ៍វត្តមាន និងការសុំច្បាប់",
    startDate: "ថ្ងៃចាប់ផ្តើម",
    endDate: "ថ្ងៃបញ្ចប់",
    exportExcel: "ទាញយកជា Excel",
    printPdf: "បោះពុម្ព / របាយការណ៍ PDF",
    searchFilter: "ការស្វែងរក និងចម្រោះ",
  }
};

export const LanguageProvider = ({ children }) => {
  const [locale, setLocale] = useState(() => {
    return localStorage.getItem('locale') || 'en'; // Default to English
  });

  useEffect(() => {
    localStorage.setItem('locale', locale);
    // Dynamically change HTML lang attribute
    document.documentElement.lang = locale;
  }, [locale]);

  const t = (key) => {
    return translations[locale][key] || key;
  };

  const getLocalizedName = (en, kh) => {
    return locale === 'kh' ? kh : en;
  };

  return (
    <LanguageContext.Provider value={{ locale, setLocale, t, getLocalizedName }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
