// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBF_z-0_I7TcKQENL8sXNQtE9WW7vsIHBg',
    appId: '1:519004002974:web:28699a5611e4055b9cb98f',
    messagingSenderId: '519004002974',
    projectId: 'khy-heng',
    authDomain: 'khy-heng.firebaseapp.com',
    storageBucket: 'khy-heng.firebasestorage.app',
    measurementId: 'G-ZHY6MDRR8B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWevBcKbvzOBDqx1znDX2WIdZepMiOHhU',
    appId: '1:519004002974:android:31c51146680b66369cb98f',
    messagingSenderId: '519004002974',
    projectId: 'khy-heng',
    storageBucket: 'khy-heng.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9J2xUTjcm_VlTf6CO-N13y2OkqJnue_o',
    appId: '1:519004002974:ios:3b1acb24a2930b5f9cb98f',
    messagingSenderId: '519004002974',
    projectId: 'khy-heng',
    storageBucket: 'khy-heng.firebasestorage.app',
    iosBundleId: 'com.hrchomnan.mobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9J2xUTjcm_VlTf6CO-N13y2OkqJnue_o',
    appId: '1:519004002974:ios:3b1acb24a2930b5f9cb98f',
    messagingSenderId: '519004002974',
    projectId: 'khy-heng',
    storageBucket: 'khy-heng.firebasestorage.app',
    iosBundleId: 'com.hrchomnan.mobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBF_z-0_I7TcKQENL8sXNQtE9WW7vsIHBg',
    appId: '1:519004002974:web:d0c0323363f74ef29cb98f',
    messagingSenderId: '519004002974',
    projectId: 'khy-heng',
    authDomain: 'khy-heng.firebaseapp.com',
    storageBucket: 'khy-heng.firebasestorage.app',
    measurementId: 'G-KZB5XKHK4Y',
  );
}
