spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://127.0.0.1:5432/khyheng_att}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgre}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
